gBirchSpeech_Welcome:: @ 81C6D78
	.string "UNUSED\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p$"

gBirchSpeech_ThisIsPokemon:: @ 81C6DF8
	.string "This is what we call a “POKéMON.”$"

gBirchSpeech_WorldInhabitedByPokemon:: @ 81C6E1A
	.string "Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\n"
	.string "I am PROFESSOR BIRCH.\p$"
	.string "We live alongside POKéMON,\n"
	.string "POKéMON can be friendly playmates,\l"
	.string "or cooperative workmates.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.$"

gBirchSpeech_AndYouAre:: @ 81C6FCB
	.string "Nice to meet you!$"

gBirchSpeech_AreYouBoyOrGirl:: @ 81C6FD8
	.string "Would you please tell me more about\n"
	.string "yourself, who are you?$"

gBirchSpeech_WhatsYourName:: @ 81C6FFA
	.string "What's your name?$"

gBirchSpeech_SoItsPlayer:: @ 81C7017
	.string "So it's {PLAYER}{KUN}?$"

gBirchSpeech_AhOkayYouArePlayer:: @ 81C7025
	.string "Thank you!\p"
	.string "{PLAYER}{KUN} please visit my lab in\n"
	.string "the small town of LITTLEROOT.\l"
	.string "We have much to discuss!$"

gBirchSpeech_AreYouReady:: @ 81C7074
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!$"
