LittlerootTown_BrendansHouse_2F_Text_172E18:: @ 8172E18
	.string "The clock is stopped...\p"
	.string "Better set it and start it!$"

LittlerootTown_BrendansHouse_2F_Text_172E4C:: @ 8172E4C
	.string "Everything's put away neatly,\p"
	.string "{RIVAL} should be coming home.\n"
	.string "please meet me downstairs.$"

UnknownString_8172F31: @ 8172F31
	.string "The bookshelf is lined entirely with\n"
	.string "books on POKéMON.\p"
	.string "It's {PLAYER}'s prized collection.$"

UnknownString_8172F85: @ 8172F85
	.string "{PLAYER} booted up the PC.$"

LittlerootTown_BrendansHouse_2F_Text_172F9A:: @ 8172F9A
	.string "{PLAYER} flipped open the notebook.\p"
	.string "ADVENTURE RULE NO. 1\n"
	.string "Open the MENU with START.\p"
	.string "ADVENTURE RULE NO. 2\n"
	.string "Record your progress with SAVE.\p"
	.string "The remaining pages are blank...$"

Text_LookCloserAtMap: @ 817303D
	.string "{PLAYER} took a closer look at the\n"
	.string "HOENN region map.$"

LittlerootTown_BrendansHouse_2F_Text_17306C:: @ 817306C
	.string "It's a Nintendo GameCube.\p"
	.string "A Game Boy Advance is connected to\n"
	.string "serve as the Controller.$"
