LittlerootTown_BrendansHouse_1F_Text_172429:: @ 8172429
	.string "See, {PLAYER}?\n"
	.string "It's very nice in here, I really like it.$"

LittlerootTown_BrendansHouse_1F_Text_172453:: @ 8172453
	.string "My husband also just bought a new clock\n"
	.string "to mark our move here…\l"
	.string "Could you be a dear and help set it?\p"
	.string "My room is just upstairs.\n"
	.string "It's the first door on the right.$"

LittlerootTown_BrendansHouse_1F_Text_172531:: @ 8172531
	.string "Dang, {PLAYER}?\p"
	.string "It seems that I have lost my truck's keys.\n"
	.string "Could you check my room for me?$"

LittlerootTown_BrendansHouse_1F_Text_172574:: @ 8172574
LittlerootTown_MaysHouse_1F_Text_172574:: @ 8172574
	.string "{PLAYER} did you forget?\p"
	.string "It's the first door on the right!$"

LittlerootTown_BrendansHouse_1F_Text_1725A3:: @ 81725A3
	.string "Hey! {PLAYER}, {PLAYER}!\n"
	.string "Quick! Come quickly!$"

LittlerootTown_BrendansHouse_1F_Text_1725C9:: @ 81725C9
LittlerootTown_MaysHouse_1F_Text_1725C9:: @ 81725C9
	.string "Look! It's PETALBURG GYM!\n"
	.string "Maybe my husband will be on!$"

LittlerootTown_BrendansHouse_1F_Text_1725FE:: @ 81725FE
LittlerootTown_MaysHouse_1F_Text_1725FE:: @ 81725FE
	.string "Oh... It's over.\p"
	.string "I think PROF. BIRCH was on,\n"
	.string "but we missed him.$"

LittlerootTown_BrendansHouse_1F_Text_172644:: @ 8172644
LittlerootTown_MaysHouse_1F_Text_172644:: @ 8172644
	.string "Now that I think about it,\n"
	.string "Is your MOM getting worried?\p"
	.string "I live right next door to you.\p"
	.string "Go home and check in with your mom.\n"
	.string "Tell her I said hi!$"

LittlerootTown_BrendansHouse_1F_Text_1726D2:: @ 81726D2
	.string "MOM: See you, honey!$"

LittlerootTown_BrendansHouse_1F_Text_1726E7:: @ 81726E7
	.string "MOM: Did you introduce yourself to\n"
	.string "PROF. BIRCH?$"

LittlerootTown_BrendansHouse_1F_Text_172717:: @ 8172717
	.string "MOM: How are you doing, {PLAYER}?\n"
	.string "You look a little tired.\p"
	.string "I think you should rest a bit.$"

LittlerootTown_BrendansHouse_1F_Text_17276B:: @ 817276B
	.string "MOM: Take care, honey!$"

LittlerootTown_BrendansHouse_1F_Text_172782:: @ 8172782
	.string "MOM: Oh? Did DAD give you that BADGE?\p"
	.string "Then here's something from your MOM!$"

LittlerootTown_BrendansHouse_1F_Text_1727CD:: @ 81727CD
	.string "Don't push yourself too hard, dear.\n"
	.string "You can always come home.\p"
	.string "Go for it, honey!$"

LittlerootTown_BrendansHouse_1F_Text_17281D:: @ 817281D
	.string "Gyao, gyao gyaoh...$"

LittlerootTown_BrendansHouse_1F_Text_172831:: @ 8172831
	.string "Gwagwah gwah...$"

LittlerootTown_BrendansHouse_1F_Text_172841:: @ 8172841
	.string "INTERVIEWER: ...We brought you this\n"
	.string "report from in front of PETALBURG GYM.$"

UnknownString_817288C: @ 817288C
	.string "There is a movie on TV.\p"
	.string "Two men are dancing on a big piano\n"
	.string "keyboard.\p"
	.string "Better get going!$"

UnknownString_81728E3: @ 81728E3
	.string "It's the instruction booklet for the\n"
	.string "RUNNING SHOES.\p"
	.string "“Press the B Button to run while\n"
	.string "wearing your RUNNING SHOES.\p"
	.string "“Lace up your RUNNING SHOES and hit\n"
	.string "the road running!”$"

LittlerootTown_BrendansHouse_1F_Text_17298B:: @ 817298B
	.string "DAD: Hm?\p"
	.string "Hey, it's {PLAYER}!\p"
	.string "It's been a while since I saw you,\n"
	.string "but you look...stronger, somehow.\p"
	.string "That's the impression I get.\n"
	.string "But your old man hasn't given up yet!\p"
	.string "Oh, yes, I have something for you.\n"
	.string "This came to you from someone named\l"
	.string "MR. BRINEY.$"

LittlerootTown_BrendansHouse_1F_Text_172A7D:: @ 8172A7D
	.string "DAD: Hm, a TICKET for a ferry?\p"
	.string "If I recall, there are ferry ports in\n"
	.string "SLATEPORT and LILYCOVE.\p"
	.string "{PLAYER}, if you have ambition as a\n"
	.string "TRAINER, go to the BATTLE TOWER.\p"
	.string "It should teach you that there is\n"
	.string "no end to a TRAINER's chosen path.$"

LittlerootTown_BrendansHouse_1F_Text_172B5E:: @ 8172B5E
	.string "I'd better get back to PETALBURG GYM.\p"
	.string "MOM, thanks for looking after the house\n"
	.string "while I'm away.$"

LittlerootTown_BrendansHouse_1F_Text_172BBC:: @ 8172BBC
	.string "MOM: That DAD of yours...\p"
	.string "He comes home for the first time in a\n"
	.string "while, but all he talks about is POKéMON.\p"
	.string "He should relax and stay a little longer.$"

UnknownString_8172C50: @ 8172C50
	.string "We bring you a special news bulletin.\p"
	.string "We've received reports of a blue FLYING\n"
	.string "POKéMON in various HOENN locales.\p"
	.string "The identity of this POKéMON has not\n"
	.string "yet been determined.\p"
	.string "We now return you to your regular\n"
	.string "movie presentation.$"

UnknownString_8172D30: @ 8172D30
	.string "We bring you a special news bulletin.\p"
	.string "We've received reports of a red FLYING\n"
	.string "POKéMON in various HOENN locales.\p"
	.string "The identity of this POKéMON has not\n"
	.string "yet been determined.\p"
	.string "We now return you to your regular\n"
	.string "movie presentation.$"

UnknownString_8172E0F: @ 8172E0F
	.string "Gau gau!$"
